version: '3.9'

services:
  authapi:
    build:
      context: ./backend/TeleCure
      dockerfile: TeleCure.AuthAPI/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - telecure-net

  productapi:
    build:
      context: ./backend/TeleCure
      dockerfile: TeleCure.ProductAPI/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - telecure-net

  frontend:
    build:
      context: ./frontend/angular-weather-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - telecure-net

networks:
  telecure-net:
    driver: bridge